### ISSUE TITLE
Retrieve information using the requests package

### ISSUE THREAD

**Issue by valbucci** [extensionsec/xcavate#10]
Before we can crawl extension data, we need to first reverse-engineer the communication between the browser and Google's servers. This communication happens in two relevant sections: the **Category Dashboard** and the **Extension Details Page**.

<details>
<summary>What is the Category Dashboard?</summary>

![The Category Dashboard](https://github.com/extensionsec/xcavate/assets/18376252/e3a55acc-1e27-4cf0-907e-c4f18ee77736)
*The Category Dashboard, containing all the extensions within a specific category. **NOTE:** here is where the user needs to click on "Load more" at the end of the page for getting more data about the extensions.*

</details>

<details>
<summary>What is the Extension Details Page?</summary>

![The Extension Details Page](https://github.com/extensionsec/xcavate/assets/18376252/2f88f486-3c9b-4c06-b8da-406e877ad9f0)
*The Extension Details Page, containing all the necessary information about a specific extension.*
</details>

<details>
<summary>Reverse-Engineering the Category Dashboard: Client-Side Request</summary>

# Category Dashboard: The Client-Side Request
When the user scrolls down to the bottom of the page, extensions are not automatically loaded anymore. Instead, it is necessary to click the "Load more" button.

When analysing the POST requests sent by the browser to receive the extensions data we observe this line:

```json
[[[
    "zTyKYc",
    "[[null, [[3,\"productivity/communication\",null,null,2,[100,\"QVNMeGY3QkxTcmx3OERZMVhDSXRCNUl1aTF0R1VfTXNZQUp4YmtLZC02dGtqTjQ3b1c0ZzVhZzVjU3d2YUIwbVhoQml0SzUyVUJGbFdPYzF0MEJOU3N4cXdscllNVHdCNHBSM0lxWnV3S0V4cTNXQlk2RFVoQU1NZG9QTlVUR05TejU4THNsZGx0Z1lfWm00MmtiTWRRQ0lSRW9SbThSS1ZGYjhDeW1VamVoM2JuSnZMbE43a19WVlVCX0lVQjRCR3I2cmY4ejJTb3MxQXc0SGc2TnU5VGExRmlYcExzWXNNbC1GM3p3RGo1RnI3NFdlYWtqOXB6VFhYWklIVEUwM1hyWkl3akFfS2dkY0RBPT0=\"]]]]]",
    null,
    "generic"
]]]
```

There is a nested array containing a bunch of obfuscated information. Let's unwrap it to understand how these values can be generated.

## A Single-Use Identifier
The first element of the (nested) list is `zTyKYc`. By observing the web store HTML body we find it in the following script block:

```html
<script nonce="">
var AF_initDataKeys = ["ds:0"];
var AF_dataServiceRequests = {
    'ds:0': {
        id: 'zTyKYc',
        request: [
            [null, [null, []]]
        ]
    }
};
var AF_initDataChunkQueue = [];
var AF_initDataCallback;
var AF_initDataInitializeCallback;
if (AF_initDataInitializeCallback) {
    AF_initDataInitializeCallback(AF_initDataKeys, AF_initDataChunkQueue, AF_dataServiceRequests);
}
if (!AF_initDataCallback) {
    AF_initDataCallback = function(chunk) {
        AF_initDataChunkQueue.push(chunk);
    };
}
</script>
```

There is various `<script nonce>` tags in the body, but this appears to be the first one. Interestingly, the variable names are not obfuscated, which may help us identify the location of this nonce.

## More JSON Data Within a String

Going forward, we have a string value containing other information. If we decompose it, it will look like this:

```json
[[
	null,
	[[
		3,
		"productivity/communication", // The category and sub-category
		null,
		null,
		2,
		[
			32, // Amount of extensions requested by the client
"QVNMeGY3QkxTcmx3OERZMVhDSXRCNUl1aTF0R1VfTXNZQUp4YmtLZC02dGtqTjQ3b1c0ZzVhZzVjU3d2YUIwbVhoQml0SzUyVUJGbFdPYzF0MEJOU3N4cXdscllNVHdCNHBSM0lxWnV3S0V4cTNXQlk2RFVoQU1NZG9QTlVUR05TejU4THNsZGx0Z1lfWm00MmtiTWRRQ0lSRW9SbThSS1ZGYjhDeW1VamVoM2JuSnZMbE43a19WVlVCX0lVQjRCR3I2cmY4ejJTb3MxQXc0SGc2TnU5VGExRmlYcExzWXNNbC1GM3p3RGo1RnI3NFdlYWtqOXB6VFhYWklIVEUwM1hyWkl3akFfS2dkY0RBPT0=" // Base64-encoded token
		]
	]]
]]
```

## The Base64 Token
This part seems to be more challenging. When the string `QVNMeGY3QkxTcmx3OERZMVhDSXRCNUl1aTF0R1VfTXNZQUp4YmtLZC02dGtqTjQ3b1c0ZzVhZzVjU3d2YUIwbVhoQml0SzUyVUJGbFdPYzF0MEJOU3N4cXdscllNVHdCNHBSM0lxWnV3S0V4cTNXQlk2RFVoQU1NZG9QTlVUR05TejU4THNsZGx0Z1lfWm00MmtiTWRRQ0lSRW9SbThSS1ZGYjhDeW1VamVoM2JuSnZMbE43a19WVlVCX0lVQjRCR3I2cmY4ejJTb3MxQXc0SGc2TnU5VGExRmlYcExzWXNNbC1GM3p3RGo1RnI3NFdlYWtqOXB6VFhYWklIVEUwM1hyWkl3akFfS2dkY0RBPT0=` is decoded from base64 another weird string is produced:
`ASLxf7BLSrlw8DY1XCItB5Iui1tGU_MsYAJxbkKd-6tkjN47oW4g5ag5cSwvaB0mXhBitK52UBFlWOc1t0BNSsxqwlrYMTwB4pR3IqZuwKExq3WBY6DUhAMMdoPNUTGNSz58LsldltgY_Zm42kbMdQCIREoRm8RKVFb8CymUjeh3bnJvLlN7k_VVUB_IUB4BGr6rf8z2Sos1Aw4Hg6Nu9Ta1FiXpLsYsMl-F3zwDj5Fr74Weakj9pzTXXZIHTE03XrZIwjA_KgdcDA==`.

Judging by the final padding characters (i.e. `==`) this string appears to have some form of base64 encoding. However, when decoding it again we get an error. I also attempted decoding it using the base64url, but the result is unreadable. This could mean that the data is compressed, or perhaps Google used a proprietary form of encoding. Potentially both. 

Nevertheless, this string was sent on the client-side, which makes me think that it ~~must have been computed locally~~, [[#Hunting Down The Token|or may have been sent by the server]].

### Hunting Down The Token
Upon further review, I attempted to reload the extensions section (for this instance it was the URL `https://chromewebstore.google.com/category/extensions/productivity/communication`).
The server response appears in line with what is described in [[#Category Dashboard The Server-Side Response]], with a minor, yet significant difference: the token can be observed in the end of the JSON string containing the extension data. This is the decoded value without escape characters:
```
QVNMeGY3QVl1aUJKTVBESlpNYzdpWUl6dEdYeGcxSkM1dHB0MEF1U2pGRnY4OXpPaDNFSTg1MTM5YjBYQXlxZDVLcjVYejhhTEgzY01ZODJyYlZfdm1hdHRORE4ta2s1dWFFMXcybVdsYnREeU9YSG9GRTBYYTVyRGhabG9hZ0x4am1Yb1FTb0F6cm9oNXVlYkpWV0tQeGdSczhDdjZBMDFya1dMT1dtV0s1MEQzYkpXUE43clhQYmtDSUg4QnU5aHozYjZqWk92US10MVhOd1lIQkk3dFZOU0l1ek1IaXJVM2pubjE4Njl1WUVLR3NDSFc0TWZqU3VJMFZBRUk4YXFZVmxjN2h1N21NYUpBPT0=
```

> Notice that this value is different from the one outlined above. This is because it is not a fixed token and is regenerated by the Google API each time the category page is accessed.

**Question**: *Is this going to be a problem?* Considering the anti-crawling policies of Google, I wouldn't be surprised if this was a method to prevent users from mapping all the extensions in a category from a single session. **Further testing is required to investigate this**.  
</details>

<details>
<summary>Reverse-Engineering the Category Dashboard: The Server-Side Response</summary>
# Category Dashboard: The Server-Side Response
After the client browser has sent its [[#Category Dashboard The Client-Side Request|POST request]], the server response will contain the extension data.

By unpacking the values, some meaning about this data can be inferred:

```json
[[
	"wrb.fr",
	"zTyKYc", // Nonce
	"...", // JSON data encoded in a string
	null,
	null,
	null,
	"1"
]]
```

Let's now unpack the JSON string:
```json
[[[[
	null,null,null,null,null,null,null,null,null,null,null,null,null,
	[[[
		[[
			"acmkailckjgackliddhdencebmfgoehl", // The identifier
			"https://...", // URL to the icon
			"Blocdrive", // The name
			5, // The rating average
			7, // The rating count
			"https://...", // URL to the thumbnail image
			"Blocdrive Gmail Extension...", // The description
			null, // URL to the extension website
			null, // Unknown boolean
			null,
			null,
			[], // Unknown, but could be the the related extensions
			1,
			null,
			11 // User estimate
			// Sometimes there is an additional boolean value here, but I only saw it when it was set to true; otherwise, the value seems to be missing
		]]
	]]]
]]]]
```

Unfortunately, much of the data that could be gathered before appears to now be unavailable. However, the extension identifier is enough to collect all the required information from each extension's detail page.
</details>

> **TODO:** Reverse-Engineer the communication between client and server in the _Extension Details Page_.

**Comment by Yang-Nankai** [comment]
I found that the new Web Store has changed its interface compared to the original, but the **token mechanism** has not changed.

### How to get the extension information list.

When the user scrolls down to the bottom of the page, extensions are not automatically loaded anymore. Instead, it is necessary to click the "Load more" button.

Anaylzing the POST requests found that it was similar to the original one.

```
[[["zTyKYc","[[null,[[3,\"productivity/communication\",null,null,2,[32,\"QVNMeGY3RGhKMEVtb2F3em52akhnQlBWMkIyQjJvS3h5djZ6U1dqakUtNmhxdE1CdmVvRWhPR3U2bnRWN2FjMGp5Y2NlRkYxZDBTdWtmV0JYS1RQRjI5dDluY3h1R2dwMERpYy10Y0hvT3BISEZ4aWpyQnh5RXVHVFJENzB6NjFYMmxTeGdVRHFzRnNObkdaWE9nNzZjWTh0YzRoek5wYU0zTkFlZGhaalBDSklEUkdNb1VxY0hZQllKSjVFT2l3M1hCVUhad3VHSTB5cUJITkV5akwxUVplek16eGRXd2xxZUNBUWJuU2ZvY0ZJdkVMY2UzLUc5YVBIRnp1ckRzYzVSMng4SDRk\"]]]]]",null,"generic"]]]
```

The `f.req` parameter is what we need to focus on, here `zTykYc` is like a string describling the funtion, beacuse I have seen similar strings at many interface.

The `productivity/communication` represents which **category**. The new category is different from the original one. It is mainly divided into three major categories: Productivity, Lifestyle, Make Chrome Yours. Each major category includes many small categories.

The `32` represents the number of extensions' information captured. Unlike the old version, the new version does not seem to be able to capture more than 150 pieces at a time(the old version limited to 500).

The `QVNMeGY3RGhKMEVtb2F3em52akhnQlBWMkIyQjJvS3h5djZ6U1dqakUtNmhxdE1CdmVvRWhPR3U2bnRWN2FjMGp5Y2NlRkYxZDBTdWtmV0JYS1RQRjI5dDluY3h1R2dwMERpYy10Y0hvT3BISEZ4aWpyQnh5RXVHVFJENzB6NjFYMmxTeGdVRHFzRnNObkdaWE9nNzZjWTh0YzRoek5wYU0zTkFlZGhaalBDSklEUkdNb1VxY0hZQllKSjVFT2l3M1hCVUhad3VHSTB5cUJITkV5akwxUVplek16eGRXd2xxZUNBUWJuU2ZvY0ZJdkVMY2UzLUc5YVBIRnp1ckRzYzVSMng4SDRk` represents **the starting placce**. In detailed terms, it means: number all  the extensions in the database, like 1,2,3,4... and then when it first starts loading, if the above `limit` is 10, then the extensions 1-10 will be loaded, and then after we click **Load more**, the extensions 11-20 will be loaded later. The maning of this string represents the starting position of 11, telling us which position we should start from to load extensions' info. 

After reverse engineering analysis, it was found that this string was not calculated locally, but was actually sent by the server with the last response. Therefore, when the 1-10 extensions' info was requested for the first time, the place was an empty string, and then returned then content contians a similar string, which must be included in the next request 11-20. During the actual test, this string is related to start(The meaning of start is explained above), so it can be reused, so that we can perform concurrent crawling. At the same time, this string may also be related to the timestamp, because for the same start, but this string is different, but fortunately, no matter which one can be used for a long time.

In order to explain it more clearly, I will show it with pictures below.

The following is the first time a certern category is requested:

![image](https://github.com/extensionsec/xcavate/assets/100209158/f06dc7d9-d33d-48f3-8513-a6bec38164a8)

The result of the response packet obtained is (the string in the header is removed, and only an extension information is retained).

```
15360  // the message size
[
    [
        "wrb.fr",
        "zTyKYc",   // Operator
        "[[[[null,null,null,null,null,[[[[[[\"majdfhpaihoncoakbjgbdhglocklcgno\",\"https://lh3.googleusercontent.com/Rm5hcKXvm9Prc-vyHzNGRpRVPxZAKQiiKPDNWW4Sn-MOm_-TxDOcKqNDpHUOYZBVidpnqWt22Wjwz9vtgW8nq-9Mrw\",\"Free VPN for Chrome - VPN Proxy VeePN\",4.714345920431557,11864,\"https://lh3.googleusercontent.com/ltTFtkBJPMbjBC5B7YcqmZOWCIXo_HXwkmK0rP1baQXVPFB-izgElxEOBnvTbgxHX4q-sNEwOzidy1vOnTRhli3xgA\",\"Fast, ultra secure, and easy to use VPN service to protect your privacy online. Enjoy Unlimited Traffic and Bandwidth!\",\"veepn.com\",true,null,null,[],1,null,6000000,true]]]]]]]]],null,[\"QVNMeGY3QlRaTlhOM0xlODhaSTNqYmttUUF0a2lMQVJKVVU5ZmhTSFBodGZna1BGZHBhVEsxWGxxbng2eHJRPQ\\u003d\\u003d\",null,null,44400]]", 
        null,
        null,
        null,
        "generic"
    ],
    [
        "di",
        97
    ],
    [
        "af.httprm",
        97,
        "-4476475136960508809",
        6
    ]
]
```
After cleaning up some irrelevant things and formatting:

```
[
    [
        [
            [
                null,
                null,
                null,
                null,
                null,
                [
                    [
                        [
                            [
                                [
                                    [
                                        \"majdfhpaihoncoakbjgbdhglocklcgno\",  // extension id
                                        \"https://lh3.googleusercontent.com/Rm5hcKXvm9Prc-vyHzNGRpRVPxZAKQiiKPDNWW4Sn-MOm_-TxDOcKqNDpHUOYZBVidpnqWt22Wjwz9vtgW8nq-9Mrw\",  // extension url
                                        \"Free VPN for Chrome - VPN Proxy VeePN\",  // extension name
                                        4.714345920431557,  // rating score
                                        11864,  // rating count
                                        \"https://lh3.googleusercontent.com/ltTFtkBJPMbjBC5B7YcqmZOWCIXo_HXwkmK0rP1baQXVPFB-izgElxEOBnvTbgxHX4q-sNEwOzidy1vOnTRhli3xgA\",
                                        \"Fast, ultra secure, and easy to use VPN service to protect your privacy online. Enjoy Unlimited Traffic and Bandwidth!\",  // description
                                        \"veepn.com\",  // extension url
                                        true,
                                        null,
                                        null,
                                        [],
                                        1,
                                        null,
                                        6000000,  //users
                                        true
                                    ]
                                ]
                            ]
                        ]
                    ]
                ]
            ]
        ]
    ],
    null,
    [
        \"QVNMeGY3Q3lSWXVIMDlpN0c3aXlyUXN0Q3NhbzRobmZ0T2VZTkt0enNtM1R3RDJtVkhISll2U0t2TWYwOHpwRDhJQzFsSmNxOTZhYVNsbU83dFVGbENXa2xKV2RaQThiNFlWdGd5b3dWTW1URmVWM0ExZGczNkpDRW55YzdEWHBna3AyXzlpVUg2czB4UEhaWDBRQTVhMC1xZVVlcW5OMmZpNS1fVGdidGRTenRNRjVkWlpKcVpQblF2YUtiVlhmZlNmVmEwdmhXaFRNOUxyOEhFbzRILWw4SDlRWVZBZXNsZ000TVE4WlRQLWNCaWFRelJVRjQ0ajN6Ni1QeWxZYUpLN09tVllhTGJnVjBnPT0\\u003d\",  // the next start
        null,
        null,
        44400
    ]
]
```

You can see that the Info messages obtained are less than before, but it is enough because we have another API —— detail to help us solve it.

Then we click on the POST request package sent after Load more and observe its f.req parameter part. We can find that this string is the string sent in the last response!

![image](https://github.com/extensionsec/xcavate/assets/100209158/bd809231-73bd-47d4-afd1-e3f2f09060bd)

**This is the page turning mechanism of Google Web Store.** And compared with the original version, what is more annoying is that the array returned by the response body is too nested, so we have to go through many re-indexes to find valid data, just like the following code:

```
token = parsed_next_array[2][0]
infojson = parsed_next_array[0][0][0][5][0][0]
```

This is too ugly, so we need to implement a more convenient function. I have made a small Python Script to crawl and it works.

**Comment by Yang-Nankai** [comment]
### How to get the extension details.

The interface to get extension details is shown in the figure below:

![image](https://github.com/extensionsec/xcavate/assets/100209158/83a33ef3-e24b-461d-bdd2-02335c66f4b0)

Actually, some parameters have no effect on the request, like the rpcids, source-path, _reqid, rt..., and the **f.req** is a list with four elements, but in fact, the last tree elements have no effect on getting the detail of extension. So there is a small script to get the detail:

```python
import requests
import os
import json
import io
from collections import OrderedDict
from requests.packages.urllib3.exceptions import InsecureRequestWarning
requests.packages.urllib3.disable_warnings(InsecureRequestWarning)

url = "https://chromewebstore.google.com/_/ChromeWebStoreConsumerFeUi/data/batchexecute?" \
      "&f.sid=974938402045885243" \
      "&bl=boq_chrome-webstore-consumerfe-ui_20231101.04_p0&hl=en&soc-app=1&soc-platform=1&soc-device=1&_reqid=560021" \
      "&rt=c"

headers = {
    "Host": "chromewebstore.google.com",
    "Content-Type": "application/x-www-form-urlencoded;charset=utf-8",
}

ext_req_data = '[[["xY2Ddd","[\\"knkpjhkhlfebmefnommmehegjgglnkdm\\"]",null,"1"]]]'

def get_ext_item_reps(url, req_data):
    try:
        post_data = {
            'f.req': req_data
        }
        print(post_data)
        response = requests.post(url, verify=False, headers=headers, data=post_data)
        res = response.text
        print(res)

        if response.status_code != 200:
            raise requests.RequestException(u"Status code error: {}".format(response.status_code))
        if response.status_code == 200:
            return res
    except requests.RequestException as e:
        return False

res = get_ext_item_reps(url, ext_req_data)
print(res)
```
The result is:

```

[
    [
        "knkpjhkhlfebmefnommmehegjgglnkdm",  // id
        "https://lh3.googleusercontent.com/oKryruCrQWAkoGeWAFLnYlFkNAsP7_LsC22EAA9-PbRqE_Jh1Q4OZoV4vE8CBW5p0LOCkHtnaruI9ovF7TXGE8fp", // url
        "Video Downloader professional",
        4.293918918918919, // rating score
        296, //rating count
        "https://lh3.googleusercontent.com/-AR2DrDB0h9ElGhjXxb_MW7148DtRaiypdfNq7Tho_kRFS2WwproRfAnsZwRuJXcHDqTQcnYpF1uL4cCW16VMONz9Q", // url
        "Download online videos in various formats from any websites. Video Downloader save video and watch it later.", // description
        null,
        null,
        true,
        null,
        [
            "make_chrome_yours/functionality",
            null,
            21
        ],  // category
        1,
        true,
        300000  // users
    ],
    null,
    null,
    null,
    null,
    [
        [
            1,
            "https://lh3.googleusercontent.com/rMrvcN5IC4xg3qWt83y7Vy1naWypbQnc-uW5alFpTDQcLI1caZmoVQ-5ECUMvcTp6ML-rKpmfWgvKxYuVKhvpsuu0w"
        ],
        [
            1,
            "https://lh3.googleusercontent.com/Rvz1eNGHpXsqDHHag2BJSSUitSFrf3eGLiWQFydEXtsZVn_KG9fKXAcB4lOfdk-N2cerCoboo8V-ZWoYo0h84nuXgw"
        ],
        [
            1,
            "https://lh3.googleusercontent.com/xq_oQj6qR6xfJiA8yOfhLgfh7kmNJ-f8L0iY3E0FgIyLJU0XXFubOvbcvM2oZMJh95zITi-PDMn70smUM7zB2LDtGg"
        ],
        [
            1,"https://lh3.googleusercontent.com/HudtZhlHWvyKagyZmx9FbkQ7BRIRXqNNYT3CSUnly90zxRMRZjYF7MditvEdKKBvc7HkJtqHJ25i5_0Ru3TsXydBNss"
        ],
        [
            1,
            "https://lh3.googleusercontent.com/rsB6RrKXeTj7JO-nGr48XOXeyixYXSyPaeOPT0ZeFa29jaT-kN2rqwdCnEMoUYTI4kG5HxJZyO5CFsNz2OQ7rk18bA"
        ]
    ],  // pictures
    "Video Downloader professional for fast downloading online videos from any webpages. The popular Chrome extension supports many video formats.\\n\\nWatch favorite moments with friends or show useful guides to business partners even if you aren't online. Save interested video files to review them later on your PC.\\n\\nYou can try Video Downloader professional and notice the difference! Use extension for free without any registration. Save in different available formats and qualities according to your needs.\\n\\nExtension adds \\"download\\" button to video page, video list or embedded video. Click \\"download\\" button and select quality of the video you are gong to download. \\n\\nHow video downloader works?\\n- After installing the extension, go to a website that contains video resources.\\n- All available video files that are on the page will be detected by the extension. Once found, an number mark is shown on the extension icon indicating that media file is available for download.\\n- A green Download button will appear on the video itself, along with all the available video file sizes.\\n- You just have to choose the size of the video you want to download.\\n- Nothing complicated!\\n\\nVideo Downloader provide you an easier way to find out where the actual media file is located on the server. \\n\\nChrome professional video downloader and music downloader, you can download videos. Free, secure and easy to use.\\nvideo downloader - Best m3u8 downloader Chrome extension to download m3u8 or audio in Chrome quickly and easily.\\n\\nUse this professional video downloader for Chrome browser to get video and audio from websites you like.\\n\\nIt can download videos of any formats, including MP4, FLV, f4v, hlv, webm, mov, mkv, and etc.\\n\\nAdd this video downloader extension to Chrome browser in one minute. Click on the icon of this extension on the target website, you will begin to download in no time. It's easy, safe and free. You will download video and audio fast and free. Try it. You will like this extension.\\n\\nSupport recording mode: videos that are difficult to download conventionally can be downloaded by recording, which means it can download almost any video from any website.\\n\\nIt allows you to keep your favorite live streams! You can now download live streams to your hard drive with this video downloader!\\n\\nYou do not need to register an account to use this video downloader. You can download any video or audio without register. This video downloader is for free to use. \\n\\nIt allows you to keep the live show you love! You can download the Live broadcasts in your disk now with this video downloader!\\n\\nDownload using popup icon:\\nAvailable for downloading video files are shown after clicking popup icon of the extension.\\nNumber shown on popup icon of the extension corresponds to q-ty of video available for downloading on page.\\n\\nNote: \\nVideo Downloader is not a Youtube Downloader. Due to restrictions of the Google Web Store Policies and Developer Program Policies we can not download Youtube Videos. Thank you for understanding.\\n\\nWe really hope that our Video Downloader will be useful to you! We look forward to your feedback and ratings! Also write your suggestions for improving the functionality.",  // detial description
    null,
    true,
    1,
    [
        "romanfrancis9881@gmail.com",
        null,
        "https://sites.google.com/view/video-loader/privacy-policy",
        null,
        null,
        "video-loader.app"
    ],  // developer information
    null,
    null,
    "1.0.5",  // version
    [1674205068,681000000],  // unkown?
    "138KiB",  // file size
    ["Bahasa Indonesia","Bahasa Melayu","Deutsch","English","English (UK)","English (United States)","Filipino","Français","Kiswahili","Nederlands","Norsk","Tiếng Việt","Türkçe","català","dansk","eesti","español","español (Latinoamérica)","hrvatski","italiano","latviešu","lietuvių","magyar","polski","português (Brasil)","português (Portugal)","română","slovenský","slovenščina","suomi","svenska","čeština","Ελληνικά","Српски","български","русский","українська","עברית","فارسی\\u200e","मराठी","हिन्दी","বাংলা","ગુજરાતી","தமிழ்","తెలుగు","ಕನ್ನಡ","മലയാളം","ไทย","አማርኛ","\\u202bالعربية","中文 (简体)","中文 (繁體)","日本語","한국어"],  // language
    null,
    null,
    null,
    "{\\n\\"update_url\\": \\"https://clients2.google.com/service/update2/crx\\",\\n\\n    \\"version\\": \\"1.0.5\\",\\n    \\"manifest_version\\": 3,\\n    \\"name\\": \\"__MSG_name__\\",\\n    \\"short_name\\": \\"__MSG_name__\\",\\n    \\"description\\": \\"__MSG_desc__\\",\\n    \\"default_locale\\": \\"en\\",\\n    \\"icons\\": {\\n        \\"128\\": \\"/img/128.png\\",\\n        \\"64\\": \\"/img/64.png\\",\\n        \\"32\\": \\"/img/32.png\\"\\n    },\\n    \\"action\\": {\\n        \\"default_icon\\": \\"/img/128.png\\",\\n        \\"default_popup\\": \\"popup.html\\"\\n    },\\n    \\"content_scripts\\": [\\n        {\\n            \\"matches\\": [\\"\\u003call_urls\\u003e\\"],\\n            \\"js\\": [\\n                \\"/js/lib/jquery-3.2.1.min.js\\",\\n                \\"/js/lib/_config.js\\",\\n                \\"/js/content.js\\",\\n                \\"/js/feedback.js\\"\\n            ],\\n            \\"css\\": [\\n                \\"/assets/btns.css\\",\\n                \\"/assets/feedback.css\\"\\n            ],\\n            \\"all_frames\\": true\\n        },\\n        {\\n            \\"matches\\": [\\"\\u003call_urls\\u003e\\"],\\n            \\"js\\": [\\n                \\"/js/content.js\\"\\n            ],\\n            \\"all_frames\\": true\\n        }\\n    ],\\n    \\"background\\": {\\n        \\"service_worker\\": \\"js/serviceWorker.js\\"\\n    },\\n    \\"permissions\\": [\\n        \\"tabs\\",\\n        \\"downloads\\",\\n        \\"storage\\",\\n        \\"webRequest\\"\\n    ],\\n    \\"host_permissions\\": [\\n        \\"\\u003call_urls\\u003e\\"\\n    ],\\n    \\"web_accessible_resources\\": [\\n        {\\n            \\"resources\\": [\\n                \\"img/*\\"\\n            ],\\n            \\"matches\\": [\\n                \\"\\u003call_urls\\u003e\\"\\n            ]\\n        }\\n    ]\\n}\\n",  // manifest file
    true,
    [
        [
            "dkbccihpiccbcheieabdbjikohfdfaje",
            "https://lh3.googleusercontent.com/VmcqHAJnD22xrNXwfNOYnMeBNntmGVeHkTMZlnb30SggCbcwpFi3dC35LhXE1WF7kSxcWLhDj_LifsUMptxkTgcquUA",
            "Video Downloader for U",4.471698113207547,371,"https://lh3.googleusercontent.com/pVBEjIcIWQf50fi8pxbV-2AgZlevywMeSrQOZ4Avi4vETAu2sdfMoLve2KvB97QkV6JVCYxxRRDOBzKVF7Yihwh8IA",
            "Video downloader extension allows users to save videos from various online platforms in just a few clicks. Save videos for free.",
            "videounit.net",
            null,
            null,
            null,
            [],
            1,
            null,
            3000000,
            true
        ],
        [
            "mdkiofbiinbmlblcfhfjgmclhdfikkpm",
            "https://lh3.googleusercontent.com/eIfpy02zm5RfJ1wNqv5ue0uEYOisRSwoZFDlw-liNOgLOGTlauA12Hz46r49FxIZDwfw4_I3QpkOtolLIc9lEo-IiMo",
            "Video downloader Plus",
            4.127035830618892,
            307,
            "https://lh3.googleusercontent.com/Baqb6SljS1_Y0sBuyjV0s4lP5Stq5eDTwm5ksstXEePe8RxOX4CW6IfCNviN9ABfWIPPadQbpXabn5-SiQHoH3a3EQs",
            "We offer a free online video downloader tool to download any video from the web instantly for free. Download video in a few clicks!",
            null,
            null,
            null,
            null,
            [],
            1,
            null,
            500000
        ]
    ],  // related extensions' information
    null,
    null,
    null,
    null,
    "88",
    null,
    1,
    null,
    null,
    null,
    "https://sites.google.com/view/video-loader/privacy-policy",
    null,
    null,
    true
]
```

I don’t know the meaning of some parameters, but I’m sure we can also get extension detailed information, such as the contents of its manifest file.

**Obtaining comments is the same as above.**

**Comment by valbucci** [comment]
![ScraperArchitecture](https://github.com/extensionsec/xcavate/assets/18376252/e86c90ff-4ce9-4c7c-8339-eb11e98d0251)
*The planned architecture for the `data_collection` module*

# Worker Threads
#TODO
The data collection process will run continuously to crawl data. This will be handled by three worker classes which can be spawned in parallel over multiple threads.
- [ ] **ScraperWorker** collects extension details in bulk from the category pages of web stores. The resulting dataset is used to insert a list of `ScrapedExtension` objects in the `DATA_QUEUE`.
- [ ] **DatabaseWorker** takes an element from the `DATA_QUEUE` and stores it into the database via the `DatabaseHandle`. If a `ScrapedExtension` element has not been already downloaded, is missing some values, or requires an update, it is first inserted in the `COLLECTION_QUEUE`. Secondly, the data contained in the object is stored in the SQLite database. If a `CrxArchiveData` object is retrieved from the queue, it is stored in the Neo4j database.  
- [ ] **ArchiveWorker** takes a `ScrapedExtension` element form the `COLLECTION_QUEUE`. It downloads the CRX archive and stores it via the `ArchiveHandle` class. The `ArchiveHandle` class extracts the JavaScript code logic via the `ArchiveProcessor` class. The resulting metadata is stored in a `CrxArchiveData` object, which is inserted back into the `DATA_QUEUE`. If the extension details were updated, the resulting `ScrapedExtension` object is also inserted back into the `DATA_QUEUE`. 


# Store Scraping Classes 
The web store endpoint of the data collection system are scraping classes specialised for each web store. These are:
- [ ] `ChromeScraper` #high-priority 
- [ ] `FirefoxScraper` #low-priority 
- [ ] `SafariScraper` #low-priority 

Each of these classes inherits from the abstract class `StoreScraper`:

```python
class StoreScraper:


	def get_categories(self):
		"""Gets the list of available categories."""


	def get_metadata(self, category:str, collect_amount:int) -> tuple:
		"""Collects online metadata for a given amount of extensions."""


	def store_metadata_generator(self, 
								 category:str, 
								 limit:Optional[int]) -> Generator[tuple]:
		"""Continuously yields all extension metadata scraped online."""
```


# Metadata Wrapping Classes
## ScrapedExtension
To facilitate data handling, the extension metadata produced by a `StoreScraper` instance will be stored in a browser-specific class inheriting from the abstract class `ScrapedExtension`:

```python

class ScrapedExtension:
	"""
	The details of a browser extension scraped from its online store
	
	Attributes:
		identifier: unique identifier
		name: public extension name defined by the developer
		version: release version
		version_name: printable release version
		last_update: date on which the last update was released
		description: description provided by the developer explaining what the
			extension does
		category: category to which the extension was assigned
		rating_average: online star rating expressed between 1 and 5
		rating_count: amount of online ratings provided by users
		user_estimate: user count estimated by the online store
		manifest: JSON manifest represented as a dictionary
		byte_size: number of bytes used by the extension's CRX archive
		developer_name: the developer username
		recommended_extensions: list of similar extensions recommended by the
			online store (aka related extensions)
		developer_extensions: list of other extensions released by the developer
	
	"""


	@classmethod
	def build_scraped_extension(cls,
								identifier:str,
								name:Optional[str],
								version:Optional[str],
								version_name:Optional[str],
								last_update:Optional[date],
								description:Optional[str],
								category:Optional[str],
								rating_average:Optional[float],
								rating_count:Optional[int],
								user_estimate:Optional[int],
								manifest:Optional[dict],
								byte_size:Optional[int],
								developer_name:Optional[str],
								recommended_extensions:Optional[list],
								developer_extensions:Optional[list]) -> Self:
	"""Instantiates a new StoreScraper object given the provided details."""			

	def download(self, download_path:str) -> Optional[HTTPError]:
		"""
		Download the extension's archive in the given path.
		
		Returns:
			None if successful, otherwise the raised HTTPError.
		"""


	def update_details(self) -> tuple[Optional[HTTPError], bool]:
		"""
		Scrapes the extension's online details.
		
		Returns:
			A tuple with the following details:
				0 -> if successful None, otherwise the raised HTTPError.
				1 -> True if the details were updated, false otherwise.
		"""

```


## ArchiveData
#TODO


# Databases

## SQLite
The SQLite database is used to store data about the extensions, their snapshots, the available categories, and some metadata about the archives. 

## Neo4j
The Neo4j graph database is used to store Manifests and ASTs related to each CRX archive. Eventually the whole database is to be migrated to Neo4j
